'''You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''





# My logic 

class Solution(object):
    def findTheDifference(self, s, t):
        freq = {}
        for ch in s:
            freq[ch] = freq.get(ch, 0) + 1
        for ch in t:
            if freq.get(ch, 0) == 0:
                return ch
            freq[ch] -= 1







# Best solution

# class Solution(object):
#     def findTheDifference(self, s, t):
#         for ch in t:
#             if s.count(ch) < t.count(ch):
#                 return ch






# Fast solution
# class Solution(object):
#     def findTheDifference(self, s, t):
#         res = 0
#         for ch in s + t:
#             res ^= ord(ch)
#         return chr(res)
